theme: jekyll-theme-minimal
title: [DHP D258]
logo: figures/network.png
description: [Gathering, visualizing and modeling data in context for diplomacy and global affairs.]
url: https://annahaensch.github.io/