theme: jekyll-theme-minimal
title: [Data Science for Global Applications]
logo: figures/network.png
description: [Gathering, visualizing and Mmdeling data in context for Law, diplomacy and global affairs]
url: https://annahaensch.github.io/