theme: jekyll-theme-cayman
title: [Data Science for Global Applications]
logo: figures/network.png
description: [Studying data science in context for diplomacy and global affairs.]
url: https://annahaensch.github.io/
